# Default values for notification-gateway.

# Number of Pod Replicas desired
replicaCount: 2

# Enables debug mode
debug:
  enable: false

# Required Values for the Chart
required:
  # Define the docker image
  image:
    # The repository where is stored the docker image "notification-gateway"
    repository: europe-west3-docker.pkg.dev/gematik-all-infra-prod/demis-dev
    # The name of the image
    name: notification-gateway
    # Overrides the image tag whose default is the chart appVersion.
    # If not given, the Chart AppVersion will be used
    tag: null

# Define custom configuration values
# The Entries will be read from the given (external) Secrets and injected in the container with the same name.
# IMPORTANT: these values must be defined in the Secret Objects
config:
  # The (external) Secret Objects containing the API Key entry
  secret:
    # The (external) Secret for API Keys
    passwords:
      # The name of the (external) Secret for Passwords and the entries to be used and mapped
      name: gateway-secret
      entries:
        AUTH_CERT_PASSWORD: AUTH_CERT_PASSWORD
        TEST_AUTH_CERT_PASSWORD: TEST_AUTH_CERT_PASSWORD
        TRUSTSTORE_PASSWORD: TRUSTSTORE_PASSWORD
        TOKEN_CLIENT_LAB: TOKEN_CLIENT_LAB
    # The (external) Secret for Database
    keystores:
      # The name of the (external) Secret for Keystores/Trustores and the entries to be used and mapped
      # These values are mounted as files
      name: gateway-keystores
      entries:
        truststore.jks: truststore.jks
        keystore.p12: keystore.p12
        test_keystore.p12: test_keystore.p12

# Extra Labels to be added
# E.g.
# customLabels:
#   my-label: my-label-value
customLabels: {}

# Extra labels for deployments
deploymentLabels: {}

# Extra Environment Variables to be defined
# customEnvVars
#   key: value
customEnvVars:
  TRUSTSTORE_FILE: "/app/config/notification-gateway/certs/truststore.jks"
  AUTH_CERT_KEYSTORE: "/app/config/notification-gateway/certs/keystore.p12"
  TEST_AUTH_CERT_KEYSTORE: "/app/config/notification-gateway/certs/test_keystore.p12"
  GATEWAY_SERVER_PORT: "8080"
  # new checkboxes at hospitalization to copy the address and contact data
  FEATURE_FLAG_NOTIFICATIONS_7_3: "false"
  FEATURE_FLAG_SNAPSHOT_5_3_0_ACTIVE: "false"
  FEATURE_FLAG_PORTAL_ERROR_DIALOG_FILTERING: "false"
  RPS_BASE_URL: http://report-processing-service.demis.svc.cluster.local/
  NES_BASE_URL: http://notification-processing-service.demis.svc.cluster.local/
  FEATURE_FLAG_NEW_API_ENDPOINTS: "false"
  FEATURE_FLAG_FOLLOW_UP_NOTIFICATION: "false"


# Define custom Container Entrypoint and Arguments (e.g. JVM Tuning)
# If not given, the Entrypoint defined in Dockerfile will be used
application:
  entrypoint: ["java"]
  parameters: ["-XX:ActiveProcessorCount=2", "-XX:MaxRAMPercentage=80.0", "-XX:+TieredCompilation", "-XX:+UseSerialGC", "-jar", "/app.jar"]

# The Pull Policy for the Image
imagePullPolicy: IfNotPresent
# Define Image Pull Secrets if using private registry
imagePullSecrets: []
nameOverride: "notification-gateway"
fullnameOverride: "notification-gateway"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Annotations for Workload
annotations: {}

# Annotations for Pods
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8080"

# Pod Security Context - applies to all containers in a Pod
podSecurityContext:
  # The GID to tell the Kubelet to modify permissions of a volume owned by a pod
  fsGroup: 10000
  # Determines when to apply fsGroup actions - "Always" is the default
  fsGroupChangePolicy: "OnRootMismatch"
  # Which GID container process is assigned
  runAsGroup: 10000
  # Determine whether container process starts as root (UID 0)
  runAsNonRoot: true
  # Which UID container process is assigned
  runAsUser: 10000

# Container Security Context for a single container - Takes precedence over PodSecurityContext
securityContext:
  #defines whether container can be granted privileges beyond the parent process spawing the process
  allowPrivilegeEscalation: false
  #Define whether the container has privileged access e.g. CAP_SYS_ADMIN capability and SELinux spc_t type
  privileged: false
  #Usually no longer required. Determines whether /proc is masked to the container. Do not mount /proc from a host to a container
  procMount: Default
  # The SELinux context to be applied to the container. Must not be explicitly set to Unconfined.
  seccompProfile:
    type: "RuntimeDefault"
  #Which GID container process is assigned
  runAsGroup: 10000
  # Determine whether container process starts as root (UID 0)
  runAsNonRoot: true
  #Which UID container process is assigned
  runAsUser: 10000
  # Sets the file system as read-only
  readOnlyRootFilesystem: true
  #Ability to remove and /or add Linux Capabilities
  capabilities:
    drop:
    - all

service:
  type: ClusterIP
  ports:
    http: 8080

# Resources
resources:
  limits:
    memory: "500Mi"
  requests:
    cpu: "100m"
    memory: "500Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

istio:
  enable: true
  validateJwt: true
