fullName: notification-gateway
service:
  type: ClusterIP
  ports:
    http: 8080
istio:
  virtualService:
    gateways: {}
    http:
      match:
        - headers:
            gateway-request:
              exact: "true"
          uri:
            prefix: /gateway/notification/api/ng
      rewrite:
        uri: /api/ng
      timeout: null
      retries:
        enable: false
#        attempts: 3
#        perTryTimeout: 5s
        retryOn: null
    hosts: {}
  subsets:
    main:
      version: 1.0.0
      weight: "100"
# activate Traffic mirroring, also called shadowing with the following lines
#      mirror:
#        version: 1.1.0
#        mirrorPercentage: 0
